// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package test1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Info                 *Info    `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type PhoneNumber struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type Address struct {
	Street               string   `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	Zipcode              string   `protobuf:"bytes,3,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

type Info struct {
	Phone                *PhoneNumber `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              *Address     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetPhone() *PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *Info) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

// Our address book file is just one of these.
type DbData struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DbData) Reset()         { *m = DbData{} }
func (m *DbData) String() string { return proto.CompactTextString(m) }
func (*DbData) ProtoMessage()    {}
func (*DbData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *DbData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbData.Unmarshal(m, b)
}
func (m *DbData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbData.Marshal(b, m, deterministic)
}
func (m *DbData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbData.Merge(m, src)
}
func (m *DbData) XXX_Size() int {
	return xxx_messageInfo_DbData.Size(m)
}
func (m *DbData) XXX_DiscardUnknown() {
	xxx_messageInfo_DbData.DiscardUnknown(m)
}

var xxx_messageInfo_DbData proto.InternalMessageInfo

func (m *DbData) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "test1.Person")
	proto.RegisterType((*PhoneNumber)(nil), "test1.PhoneNumber")
	proto.RegisterType((*Address)(nil), "test1.Address")
	proto.RegisterType((*Info)(nil), "test1.Info")
	proto.RegisterType((*DbData)(nil), "test1.DbData")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbf, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0xf1, 0x8f, 0xd8, 0xf8, 0xd4, 0x66, 0xb8, 0xa1, 0x78, 0xab, 0x31, 0x04, 0x34, 0xb9,
	0xd4, 0x1d, 0x3b, 0x15, 0xb2, 0x74, 0x68, 0x09, 0x1a, 0xbb, 0xd9, 0xf1, 0x85, 0x18, 0x6a, 0x49,
	0x48, 0xea, 0xd2, 0xbf, 0xbe, 0xf8, 0x22, 0x43, 0xb7, 0x3b, 0xde, 0xe3, 0xfb, 0x8e, 0x83, 0x3b,
	0x7f, 0xbe, 0xd2, 0x32, 0x74, 0xd6, 0x99, 0x60, 0x70, 0x17, 0xc8, 0x87, 0xe7, 0xf6, 0x03, 0x8a,
	0x13, 0x39, 0x6f, 0x34, 0xee, 0x21, 0x9d, 0xa7, 0x3a, 0x69, 0x12, 0x99, 0xa9, 0x74, 0x9e, 0x10,
	0x21, 0xd7, 0xc3, 0x42, 0x75, 0xda, 0x24, 0xb2, 0x52, 0x3c, 0xe3, 0x23, 0xe4, 0xb3, 0xbe, 0x98,
	0x3a, 0x6b, 0x12, 0x29, 0x7a, 0xd1, 0x31, 0xa3, 0x7b, 0xd7, 0x17, 0xa3, 0x38, 0x68, 0x0f, 0x20,
	0x4e, 0x57, 0xa3, 0xe9, 0xf3, 0x67, 0x19, 0xc9, 0xe1, 0x03, 0x14, 0x9a, 0x27, 0xe6, 0x56, 0x2a,
	0x6e, 0xed, 0x2b, 0x94, 0x6f, 0xd3, 0xe4, 0xc8, 0xfb, 0xb5, 0xe2, 0x83, 0x23, 0x0a, 0x51, 0x14,
	0x37, 0xac, 0xa1, 0xfc, 0x9d, 0xed, 0xd9, 0x4c, 0xc4, 0xb6, 0x4a, 0x6d, 0x6b, 0xfb, 0x05, 0xf9,
	0x6a, 0x44, 0x09, 0x3b, 0xbb, 0xba, 0x98, 0x2d, 0x7a, 0x8c, 0xd7, 0xfc, 0xf3, 0xab, 0x5b, 0x01,
	0x25, 0x94, 0xc3, 0x4d, 0xc7, 0x12, 0xd1, 0xef, 0x63, 0x37, 0x1e, 0xa1, 0xb6, 0xb8, 0x7d, 0x82,
	0xe2, 0x38, 0x1e, 0x87, 0x30, 0xe0, 0x01, 0x0a, 0x4b, 0xc6, 0x7e, 0xaf, 0xf8, 0x4c, 0x8a, 0xfe,
	0x7e, 0xc3, 0xf3, 0xb7, 0x54, 0x0c, 0xc7, 0x82, 0xbf, 0xf9, 0xf2, 0x17, 0x00, 0x00, 0xff, 0xff,
	0xfb, 0x1b, 0x19, 0x19, 0x5d, 0x01, 0x00, 0x00,
}
